
services:
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest

  backend:
    build: /backend
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - redis
    volumes:
      - static:/app/static

  celery:
    build: /backend
    command: celery -A payment_system worker --loglevel=info -P eventlet
    depends_on:
      - postgres
      - redis


volumes:
  postgres-data:
  static: